const projects = [
  { eyebrow: "Daily games · 2026", title: "Games", description: "A growing arcade of daily logic and word games—designed to be welcoming on the first play and rewarding on the tenth.", href: "https://raphaelzstone.github.io/games/", tag: "Play the arcade", className: "games-card" },
  { eyebrow: "In progress", title: "A useful life on the internet", description: "This is the beginning of a durable home for projects, notes, experiments, and the things worth sharing along the way.", href: "#now", tag: "What I’m building", className: "notes-card" },
];

export default function Home() {
  return <main>
    <nav className="site-nav" aria-label="Primary navigation">
      <a className="wordmark" href="#top" aria-label="Raphael Zstone home"><span className="wordmark-mark" aria-hidden="true">RZ</span><span>Raphael Zstone</span></a>
      <div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="#now">Now</a><a className="nav-github" href="https://github.com/raphaelzstone" target="_blank" rel="noreferrer">GitHub <span aria-hidden="true">↗</span></a></div>
    </nav>
    <section className="hero" id="top">
      <div className="hero-copy"><p className="kicker"><span className="kicker-dot" /> Personal site · New York</p><h1>Making thoughtful things for the web.</h1><p className="hero-intro">I’m Raphael Zstone. This is my evolving home for digital projects, small experiments, and the ideas I&apos;m excited to keep building.</p><div className="hero-actions"><a className="button button-primary" href="#work">See selected work <span aria-hidden="true">↓</span></a><a className="button button-text" href="https://raphaelzstone.github.io/games/">Play my games <span aria-hidden="true">↗</span></a></div></div>
      <div className="hero-art" aria-hidden="true"><div className="art-sun" /><div className="art-window"><span className="window-label">currently</span><strong>Building<br />in public</strong><span className="window-rule" /><span className="window-small">projects · games · notes</span></div><div className="art-grid"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><span className="art-orbit orbit-one" /><span className="art-orbit orbit-two" /></div>
    </section>
    <section className="section work-section" id="work"><div className="section-heading"><p className="eyebrow">Selected work</p><h2>Things I&apos;ve made—and things I&apos;m making room for.</h2><p>Each project is an excuse to make something clear, playful, and genuinely useful.</p></div><div className="project-grid">{projects.map((project, index) => <a className={`project-card ${project.className}`} href={project.href} key={project.title} target={project.href.startsWith("http") ? "_blank" : undefined} rel={project.href.startsWith("http") ? "noreferrer" : undefined}><div className="project-card-art" aria-hidden="true">{index === 0 ? <><span>W</span><span>O</span><span>R</span><span>D</span></> : <><span className="paper paper-a" /><span className="paper paper-b" /><span className="paper paper-c" /></>}</div><div className="project-card-body"><p className="project-eyebrow">{project.eyebrow}</p><h3>{project.title}</h3><p>{project.description}</p><span className="project-link">{project.tag} <b aria-hidden="true">↗</b></span></div></a>)}</div></section>
    <section className="section about-section" id="about"><div className="portrait-placeholder" aria-hidden="true"><span className="portrait-initials">RZ</span><span className="portrait-caption">A real photograph can live here soon.</span></div><div className="about-copy"><p className="eyebrow">A little about me</p><h2>Curious by default. Serious about craft.</h2><p>I care about the experience around an idea: the first impression, the tiny interactions, and whether something earns a place in someone&apos;s day.</p><p>This page is intentionally a living document. As the work grows, it will become a clearer record of what I&apos;m learning, making, and looking for next.</p><a className="inline-link" href="https://github.com/raphaelzstone" target="_blank" rel="noreferrer">Follow along on GitHub <span aria-hidden="true">↗</span></a></div></section>
    <section className="section now-section" id="now"><div className="now-copy"><p className="eyebrow">Now</p><h2>Building a better home base.</h2><p>Right now I&apos;m expanding this site and the daily games arcade. This section will keep a lightweight record of the work, questions, and links that are current.</p></div><div className="now-list"><div><span>01</span><p>Growing the daily games arcade</p></div><div><span>02</span><p>Making space for longer-form notes</p></div><div><span>03</span><p>Collecting work worth showing properly</p></div></div></section>
    <footer className="site-footer"><p>© {new Date().getFullYear()} Raphael Zstone</p><div><a href="https://github.com/raphaelzstone" target="_blank" rel="noreferrer">GitHub</a><a href="https://raphaelzstone.github.io/games/">Games</a><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
