const research = [
  ['Glassy materials', 'First-principles modeling of disordered materials using density-functional-theory ensembles and high-performance computing.'],
  ['Materials discovery', 'Combining DFT, molecular dynamics, and machine learning to explore materials phase space more efficiently.'],
  ['Scientific software', 'Developing differentiable DFT methods in the JuliaMolSim ecosystem for point-defect and electrochemical-interface calculations.'],
];

export default function Home() {
  return <main>
    <nav className="nav" aria-label="Primary navigation"><a href="#top" className="wordmark">Raphael Stone</a><div><a href="#research">Research</a><a href="#experience">Experience</a><a href="#games">Games</a><a className="nav-resume" href="/Raphael-Stone-CV.pdf" target="_blank">Résumé ↗</a></div></nav>
    <section className="hero" id="top"><div className="hero-main"><p className="eyebrow">Computational materials science · Pittsburgh, PA</p><h1>Researcher, engineer, and builder.</h1><p className="lede">I&apos;m Raphael Stone, a Ph.D. student in Materials Science and Engineering at Carnegie Mellon University. I work at the intersection of computational materials, scientific software, and energy-relevant chemistry.</p><div className="actions"><a className="button primary" href="/Raphael-Stone-CV.pdf" target="_blank">Download CV <span>↓</span></a><a className="button secondary" href="https://github.com/raphaelzstone" target="_blank" rel="noreferrer">GitHub ↗</a></div></div><aside className="profile-card"><div className="profile-image"><span>RS</span></div><p className="photo-note">Headshot coming soon</p><dl><div><dt>Now</dt><dd>Ph.D. student, Carnegie Mellon</dd></div><div><dt>Focus</dt><dd>Computational materials research</dd></div><div><dt>Previously</dt><dd>University of Chicago</dd></div></dl></aside></section>
    <section className="section intro"><p className="section-number">01</p><div><p className="eyebrow">About</p><h2>I study materials problems that matter—and build tools that make the work clearer.</h2><p className="body-copy">My research spans computational modeling, electrochemistry, and materials discovery. I&apos;m especially interested in using rigorous computation to help scientists move faster from a question to a useful answer.</p></div></section>
    <section className="section" id="research"><div className="section-head"><p className="section-number">02</p><div><p className="eyebrow">Research</p><h2>Current areas of work</h2></div></div><div className="research-list">{research.map(([title, description], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
    <section className="section" id="experience"><div className="section-head"><p className="section-number">03</p><div><p className="eyebrow">Experience</p><h2>A foundation in research, computation, and energy.</h2></div></div><div className="timeline"><article><p>2024 — present</p><div><h3>Carnegie Mellon University</h3><h4>Ph.D. Student · Materials Science &amp; Engineering</h4><p>Researching efficient modeling of glassy materials, computational approaches to materials discovery, and differentiable DFT methods.</p></div></article><article><p>2021 — 2024</p><div><h3>University of Chicago</h3><h4>Research Assistant · Electrochemical Separation</h4><p>Led research on lithium and sodium selectivity in layered oxide materials for electrochemical extraction from brines and seawater.</p></div></article><article><p>2021 &amp; 2022</p><div><h3>SparkCognition</h3><h4>Research &amp; Development Intern</h4><p>Developed Python tools and quality checks for machine-learning-assisted seismic imaging on high-performance computing systems.</p></div></article></div></section>
    <section className="section credentials"><p className="section-number">04</p><div><p className="eyebrow">Education &amp; recognition</p><h2>University of Chicago, B.S. Molecular Engineering</h2><p className="body-copy">Minor in Sustainable Energy and Water Resources. Recipient of the Quad Research Scholar award and the Jeff Metcalf Research Grant.</p><a className="text-link" href="/Raphael-Stone-CV.pdf" target="_blank">View full CV ↗</a></div></section>
    <section className="games" id="games"><div><p className="eyebrow">Outside the lab</p><h2>I also make games.</h2><p>My daily games arcade is a small ongoing design practice: logic, language, clear interaction, and a little bit of delight.</p><a className="button primary" href="https://raphaelzstone.github.io/games/">Visit the games arcade ↗</a></div><div className="games-detail"><span>Daily</span><strong>Logic &amp;<br />word games</strong><p>Independent web projects by Raphael Stone</p></div></section>
    <footer><p>© {new Date().getFullYear()} Raphael Stone</p><div><a href="https://github.com/raphaelzstone" target="_blank" rel="noreferrer">GitHub</a><a href="/Raphael-Stone-CV.pdf" target="_blank">CV</a><a href="#top">Back to top ↑</a></div></footer>
  </main>;
}
